### ISSUE TITLE
Example is missing

### ISSUE THREAD

**Issue by jounathaen** [mkroening/include-transformed#1]
An example in the README or the docs on the usage would be helpful!

**Comment by mkroening** [comment]
Well the docs do include an example, although a not very elaborate one: [`include_nasm_bin!`](https://docs.rs/include-transformed/latest/include_transformed/macro.include_nasm_bin.html#examples)

I'll extend it. :+1:

**Comment by mkroening** [comment]
Are you satisfied with 7bf3c5679fc19036d72befb773b77ba214461cad? :grin:

**Comment by jounathaen** [comment]
I'm somewhat missing something like this on the top-level. The nasm macro itself is quite well documented, but it is a bit hard to get the idea when looking at the crate itself.

**Comment by jounathaen** [comment]
Maybe one thing is, that the word "transformed" in my head is not really connotated with what is happening in this crate (although it is probably correct English). Perhaps you could more explicitly state "processed by external tool" in the README/crate doc.

**Comment by mkroening** [comment]
Ah, I see. The scope of this crate are compile-time transformations in general. So instead of including a file directly with `include_bytes!`, the data is being transformed at compile-time to some other data, which is then included. The transformation might be assembling assembly source code to binary code. It is not necessarily done by external tools though, but might be any transformation which can be described in Rust code.

What do you think of https://github.com/mkroening/include-transformed/pull/2?

**Comment by jounathaen** [comment]
I think what you just wrote would be a better text than the current one in the README :-D
